services:
  productcatalog.api:
    image: ${DOCKER_REGISTRY-}productcatalogapi
    container_name: products.api
    build:
      context: .
      dockerfile: Services/Product/src/Presentation/ProductCatalog.cs/Dockerfile
    ports:
        - "7000:7000"
        - "7001:7001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_SERVER=productcatalog.db                 
      - DB_NAME=Product_DB
      - DB_USER=Admin_DB
      - DB_PASSWORD=P@ssw0rd
    depends_on:
      - productcatalog.db

  productcatalog.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: products.db_mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
      - MSSQL_PID=Express
    volumes:
      - ./.containers/products-db:/var/lib/mssql/data

  productcatalog.cash:
    image: redis:latest
    container_name: products.redis_cash
    ports:
      - "6379:3679"
    restart: always
